package com.unit2project.travel_mate_backend.controllers;


import com.unit2project.travel_mate_backend.dto.ActivityDTO;
import com.unit2project.travel_mate_backend.dto.UserDTO;
import com.unit2project.travel_mate_backend.models.Activity;
import com.unit2project.travel_mate_backend.models.Day;
import com.unit2project.travel_mate_backend.models.User;
import com.unit2project.travel_mate_backend.repositories.ActivityRepository;
import com.unit2project.travel_mate_backend.repositories.DayRepository;
import jakarta.validation.Valid;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpMethod;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.servlet.resource.NoResourceFoundException;

import java.util.List;

@RestController
@RequestMapping("/api/activities")
public class ActivityController {

    @Autowired
    ActivityRepository activityRepository;  //Type of activityRepository (variable name) is ActivityRepository(Class),
    // which is an interface that extends JpaRepository, allows CRUD on Activity entity in database.

    @Autowired
    DayRepository dayRepository;

    @GetMapping("") //base path
    public List<Activity> getAllActivities() {
        return activityRepository.findAll();// 200 response, successful retrieval
    }

    @PostMapping("/addActivity/{dayId}")
    public ResponseEntity<?> addNewActivity(@PathVariable int dayId, @RequestBody ActivityDTO activityData) throws NoResourceFoundException {
        Activity activity = new Activity(activityData.getName(), activityData.getTime(), activityData.getNotes()); //don't need id because it is auto-generated by the database
        Day day = dayRepository.findById(dayId).orElse(null);//get day from db using URL path variable
        if (day == null) {
            throw new NoResourceFoundException(HttpMethod.POST, "/" + dayId, "Day with id " + dayId + " not found"); // 404
        }

        activity.setDay(day);//sets day as parent, gives activity the foreign key of dayId
        activityRepository.save(activity); // saves the new activity to the database
        return new ResponseEntity<>(activity, HttpStatus.CREATED); // 201, successful creating
    }

    @PutMapping("/editActivity/{activityId}")
    public ResponseEntity<?> updateActivityById(@PathVariable int activityId, @RequestBody ActivityDTO activityData) throws NoResourceFoundException {
        Activity existingActivity = activityRepository.findById(activityId).orElse(null);
        if (existingActivity == null) {
            throw new NoResourceFoundException(HttpMethod.PUT, "/" + activityId, "The activity with id " + activityId + " not found");
        } else {
            existingActivity.setName(activityData.getName());
            existingActivity.setTime(activityData.getTime());
            existingActivity.setNotes(activityData.getNotes());
        }
        activityRepository.save(existingActivity);
        return ResponseEntity.ok(existingActivity);
    }


    @DeleteMapping("/deleteActivity/{id}")//deleing by unique activity id so don't need relationship to day or trip
    public ResponseEntity<?> deleteActivity(@PathVariable int id) throws NoResourceFoundException {
        Activity activity = activityRepository.findById(id).orElse(null); //only deletes the activity by id, not other ids (trip, day) b/c only queries the primary key of Activity table
        if (activity == null) { // checks if the activity with the specified id exists in the database, if not, throws an exception
            throw new NoResourceFoundException(HttpMethod.DELETE, "/" + id, "Activity with id " + id + " not found"); // 404, resource not found, activity with the specified id does not exist in the database
        } else {
            activityRepository.deleteById(id);
            return new ResponseEntity<>(HttpStatus.NO_CONTENT); // 204, successful deletion, no content to return
        }
    }



}
